# Generated by Django 4.2.7 on 2023-11-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortiwan_monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPN_Tunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('connection_count', models.CharField(max_length=255)),
                ('comments', models.CharField(max_length=255)),
                ('tun_id', models.CharField(max_length=16)),
                ('proxy_status', models.CharField(max_length=255)),
                ('proxy_expire', models.CharField(max_length=255)),
                ('proxy_outgoing_mb', models.CharField(max_length=255)),
                ('proxy_incoming_mb', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Tunnel',
        ),
    ]
