# Generated by Django 4.2.7 on 2023-12-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPsecVPN_1',
        ),
    ]
