# Generated by Django 4.2.7 on 2024-07-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_apiuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='message',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='status',
        ),
    ]
