# Generated by Django 4.2.7 on 2023-11-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_apiuser_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='username',
        ),
    ]
