# Generated by Django 4.2.7 on 2023-11-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_apiuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='issued_time',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
